#pragma config(Sensor, S1,     lightSensor,    sensorEV3_Color)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define VAL 10//Threshold value
#define TURN 710//How long it turns for
#define SLIGHT 250//Slight movement to help with the turn

void write_to_grid(int, int, int, int, int);

task main()
{
	int cond = 1;
    int j;
    int start, count;
    start = count = 0;

	while(cond == 1)
	{
		while(SensorValue(lightSensor) >= VAL) //While on WHITE
        {
            for(j = 0; j < 7; j++) //To count the amount of squares from the start position
            {
                if(SensorValue(lightSensor) > 10)
                {
                   count++; 
                }
                else
                {
                    count++;
                }

                displayBigTextLine(1, "%d squares", count);

                setMotorSync(left, right, 0, 30);//Move forward
                wait1Msec(1050);
                setMotorSync(left, right, 0, 0);//Wait
                wait1Msec(200);
                
                if(nMotorEncoder(motorB) < 90)
                {
                    cond = 0;
                }
            }
        }
        
        start = 7 - count;
        
        while(SensorValue(lightSensor) < VAL) //While on BLACK
        {
            setMotorSync(left, right, 0, 30);
            nMotorEncoder(left) = 0;
        }
	}
    
    setMotorSync(left, right, 0, -30);//back to the first square
	wait1Msec(6700);

	setMotorSync(left, right, 0, 0);//wait a moment
	wait1Msec(400);


	int i;
	int sq;
	int black, white, row, column;
	i = sq = black = white = 0;
    column = 1;
    row = 10;
	for(i=0; i<70; i++)
	{
		sq++;
		if(SensorValue(lightSensor) >10)
		{
			white++;
		}
		else
		{
			black++;
		}

		displayBigTextLine(1, "%d squares", sq);
		displayBigTextLine(3, "%d white", white);
		displayBigTextLine(5, "%d black", black);

		setMotorSync(left, right, 0, 30);//Move forward
		wait1Msec(1050);
		setMotorSync(left, right, 0, 0);//Wait
		wait1Msec(200);

		if(sq==7||sq==21||sq==35||sq==49||sq==63)//Turn right
		{
            column++;
            
            motor[left] = 50;
            motor[right] = 0;
            wait1Msec(TURN);

            setMotorSync(left, right, 0, 30);//Slightly forward to help with turn
            wait1Msec(SLIGHT);

            motor[left] = 50;
            motor[right] = 0;
            wait1Msec(TURN);
        }
        if(sq==14||sq==28||sq==42||sq==54)//Turn left
        {
            column++;
            
            motor[left] = 0;
            motor[right] = 50;
            wait1Msec(TURN);

            setMotorSync(left, right, 0, 30);//Slightly forward to help with turn
            wait1Msec(SLIGHT);

            motor[left] = 0;
            motor[right] = 50;
            wait1Msec(TURN);

		}
	}
    
    write_to_grid(start, black, white, sq, row, column);
    
    //At end of grid turn right
    motor[left] = 50;
    motor[right] = 0;
    wait1Msec(TURN);
    
    //Move forward for 10 squares
    setMotorSync(left, right, 0, 30);
    wait1Msec();
    
    //Turn right at other end
    motor[left] = 50;
    motor[right] = 0;
    wait1Msec(TURN);
    
    //Return to start position
    for(i=0; i<start; i++)
	{
        setMotorSync(left, right, 0, 30);//move forward
		wait1Msec(1050);
		setMotorSync(left, right, 0, 0);//wait
		wait1Msec(200);
    }
    
}

void write_to_file(int start, int black, int white, int sq, int row, int column)
{
    FILE *grid;
    grid = fopen("Grid.txt", "w");
    
    fprintf(grid,"Start position is at row: %d column 1\n", start);
    fprintf(grid,"Total number of rows: %d\n", row);
    fprintf(grid,"Total number of columns: %d\n", column);
    fprintf(grid,"Number of black squares: %d\n", black);
    fprintf(grid,"Number of white squares: %d\n", white);
    fprintf(grid,"Total number of squares: %d\n", sq);
    
    fclose(grid);
}
